export interface Descricao {
  id: number;
  nome: string;
}

const DescricaoPage: Descricao[] = [
  { id: 1, nome: "Acabamento cromado" },
  { id: 2, nome: "Acabamento em textura acrílica" },
  { id: 3, nome: "Alumínio pintado de branco" },
  { id: 4, nome: "Alumínio pintado de branco com vidro liso" },
  { id: 5, nome: "Bloco cerâmico rebocado com chapisco rústico ou bloco aparente" },
  { id: 6, nome: "Bloco cerâmico rebocado e pintado ou bloco de concreto aparente" },
  { id: 7, nome: "Bomba e filtro Jacuzzi, Mark Peerles ou similar" },
  { id: 8, nome: "Braços com lâmpadas em postes" },
  { id: 9, nome: "Cerâmica" },
  { id: 10, nome: "Cerâmica até o teto" },
  { id: 11, nome: "Cerâmica h=5cm" },
  { id: 12, nome: "Concreto com junta seca" },
  { id: 13, nome: "Concreto desempolado" },
  { id: 14, nome: "Fechadura elétrica no portão e motor para veículos" },
  { id: 15, nome: "Fechamento em tela de nylon ou alambrado" },
  { id: 16, nome: "Forro de gesso" },
  { id: 17, nome: "Grama" },
  { id: 18, nome: "Grama e arbustos conforme projeto" },
  { id: 19, nome: "Infraestrutura para high wall com condensadora axial" },
  { id: 20, nome: "Inox" },
  { id: 21, nome: "Intertravado emborrachado ou grama" },
  { id: 22, nome: "Itens a serem definidos" },
  { id: 23, nome: "Liso incolor" },
  { id: 24, nome: "Louça branca" },
  { id: 25, nome: "Mármore ou granito" },
  { id: 26, nome: "Mármore ou granito L=3,5cm" },
  { id: 27, nome: "Mármore ou granito com cuba em louça branca" },
  { id: 28, nome: "Metálico" },
  { id: 29, nome: "Pastilha cerâmica" },
  { id: 30, nome: "Perfil metálico pintado de branco" },
  { id: 31, nome: "Pintura acrílica" },
  { id: 32, nome: "Pintura ou textura acrílica" },
  { id: 33, nome: "Pintura PVA látex branco sobre gesso ou massa de regularização PVA" },
  { id: 34, nome: "Piso intertravado de concreto ou paralelepípedo" },
  { id: 35, nome: "Pontilhado incolor" },
  { id: 36, nome: "Pontos de luz no teto, tomadas de corrente e interruptores" },
  { id: 37, nome: "Pontos secos de comunicação e antena de TV" },
  { id: 38, nome: "Porcelanato" },
  { id: 39, nome: "Porcelanato Incesa, Lef, Incefra, Portobello ou Cecafi, ou pedra natural" },
  { id: 40, nome: "Porcelanato ou Laminado, h=5cm" },
  { id: 41, nome: "Porcelanato ou laminado" },
  { id: 42, nome: "Porta semi-oca comum com esmalte sintético" },
  { id: 43, nome: "Porta semi-oca comum pintada com esmalte sintético" },
  { id: 44, nome: "Pré-moldada ou alvenaria" },
  { id: 45, nome: "Rede aérea ou subterrânea" },
  { id: 46, nome: "Rede de água ligada ao sistema público e reservatório" },
  { id: 47, nome: "Rede de água fria em PEX e esgoto em PVC" },
  { id: 48, nome: "Rede interna ligada ao sistema público de esgoto" },
  { id: 49, nome: "Rede subterrânea com tubulação seca e shafts" },
  { id: 50, nome: "Sifão em PVC, rede de água fria e ducha higiênica em PEX" },
  { id: 51, nome: "Tela alambrado ou tela de proteção" },
  { id: 52, nome: "Textura acrílica" },
  { id: 53, nome: "Textura acrílica ou pastilha cerâmica" },
  { id: 54, nome: "Tomadas e interruptores Prime, Alumbra, Cemar ou Fame" },
  { id: 55, nome: "Torneira em PVC rígido" },
  { id: 56, nome: "Torneira para lavatório com registro e acabamento cromado" },
  { id: 57, nome: "Torneira para pia com acabamento cromado" },
  { id: 58, nome: "Torneiras e registro de gaveta com acabamento cromado" },
  { id: 59, nome: "Tubulação seca" },
  { id: 60, nome: "Vaso sanitário com caixa acoplada em louça branca" },
  { id: 61, nome: "Vinílico" },
  { id: 62, nome: "Vinílico, mármore, granito ou madeira h=5cm" }
];

export default DescricaoPage;
