export interface Item {
    id: number;
    nome: string;
}

const ItemPage: Item[] = [
    { id: 1, nome: "Acabamento Externo" },
    { id: 2, nome: "Acabamento Interno" },
    { id: 3, nome: "Ar Condicionado" },
    { id: 4, nome: "Bancada" },
    { id: 5, nome: "Borda" },
    { id: 6, nome: "Brinquedos" },
    { id: 7, nome: "Churrasqueira" },
    { id: 8, nome: "Cobogó" },
    { id: 9, nome: "Cordão de Box" },
    { id: 10, nome: "Cuba" },
    { id: 11, nome: "Drenag./pluviais" },
    { id: 12, nome: "Equipamentos" },
    { id: 13, nome: "Esquadria" },
    { id: 14, nome: "Esquadrias" },
    { id: 15, nome: "Ferragem" },
    { id: 16, nome: "Ferragens" },
    { id: 17, nome: "Gradil" },
    { id: 18, nome: "Guarda Corpo" },
    { id: 19, nome: "Iluminação das ruas" },
    { id: 20, nome: "Inst. Comunicação" },
    { id: 21, nome: "Inst. Comunic." },
    { id: 22, nome: "Inst. Elétrica" },
    { id: 23, nome: "Inst. Elétricas" },
    { id: 24, nome: "Inst. Hidráulica" },
    { id: 25, nome: "Inst. Hídrico" },
    { id: 26, nome: "Jardins" },
    { id: 27, nome: "Passeio" },
    { id: 28, nome: "Pavimentação" },
    { id: 29, nome: "Peitoril" },
    { id: 30, nome: "Piso" },
    { id: 31, nome: "Piso Deck" },
    { id: 32, nome: "Piso (Piscina)" },
    { id: 33, nome: "Portão" },
    { id: 34, nome: "Porta" },
    { id: 35, nome: "Porta externa" },
    { id: 36, nome: "Rede de Água" },
    { id: 37, nome: "Rede de comunicação" },
    { id: 38, nome: "Rede elétrica" },
    { id: 39, nome: "Rodapé" },
    { id: 40, nome: "Soleira" },
    { id: 41, nome: "Tabeira" },
    { id: 42, nome: "Tampo do balcão" },
    { id: 43, nome: "Tanque" },
    { id: 44, nome: "Teto" },
    { id: 45, nome: "Vidro" },
];

export default ItemPage;
